// <auto-generated />
namespace TranTuDat_2180607431.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KhoitaocacbangcuaIndenticy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoitaocacbangcuaIndenticy));
        
        string IMigrationMetadata.Id
        {
            get { return "202305241547400_Khoi tao cac bang cua Indenticy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
